// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class GoToGoogleAndSearchTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void goToGoogleAndSearch() {
    driver.Navigate().GoToUrl("https://www.google.com.au/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 768);
    driver.FindElement(By.CssSelector(".qarstb")).Click();
    {
      var element = driver.FindElement(By.CssSelector("center:nth-child(1) > .RNmpXc"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.Id("APjFqb")).Click();
    driver.FindElement(By.Id("APjFqb")).SendKeys("hell");
    driver.FindElement(By.CssSelector(".WggQGd b")).Click();
    driver.FindElement(By.CssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.Close();
  }
}
