# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test and Reporting
      run: |
        echo "npm install testmo"
        npm ci 
        npm install --no-save @testmo/testmo-cli
        echo "now calling the testmo API"
        npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Github Action Test Run Results" \
            --source "ga-selenium-run" \
            --results **/*.xml \
            -- dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=testoutput.xml"
        ls -LR
      env:
        TESTMO_URL: ${{ vars.TESTMO_URL }}
        TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}


# The --package-lock-only argument will only update the package-lock.json, instead of checking node_modules and downloading dependencies.
# -- npm run mocha-junit # Note space after --
# dotnet test --no-build --verbosity normal
# dotnet test --no-build --verbosity normal -- NUnit.TestOutputXml=results
# echo "=======LS: "
# ls -LR
# /home/runner/work/seleniumtestproject/seleniumtestproject
# /home/runner/work/seleniumtestproject/seleniumtestproject
# /home/runner/work/seleniumtestproject/seleniumtestproject/seleniumtestproject/bin/Debug/net8.0/results/SeleniumTestProject.xml
# /home/runner/work/seleniumtestproject/seleniumtestproject/seleniumtestproject/bin/Debug/net8.0/results/SeleniumTestProject.xml
# /home/runner/work/seleniumtestproject/seleniumtestproject/seleniumtestproject/bin/Debug/net8.0/results/SeleniumTestProject.xml
# mkdir xml-test-results
# cp /home/runner/work/seleniumtestproject/seleniumtestproject/seleniumtestproject/bin/Debug/net8.0/results/*.xml ./xml-results
