# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Generate Run Name
      run: echo date=$(TZ=':Australia/Melbourne' date '%Y%m%d-%H:%M') >> $RUN_NAME
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test and Reporting
      run: |
        RUN_NAME=$(TZ=':Australia/Melbourne' date '+%Y%m%d-%H:%M-Github Actions Run')
        npm ci 
        npm install --no-save @testmo/testmo-cli
        npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name $RUN_NAME \
            --source "ga-selenium" \
            --results ga-selenium-test-output.xml \
            -- dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=ga-selenium-test-output.xml"
      env:
        TESTMO_URL: ${{ vars.TESTMO_URL }}
        TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}


# The --package-lock-only argument will only update the package-lock.json, instead of checking node_modules and downloading dependencies.
# 
# **/*test*.xml \