
name: Basic Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore, Build & Test
      run: |        
        dotnet build
        dotnet test --no-build --logger:"junit;LogFilePath=test-output.xml"

