
name: Basic Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore, Build & Test
      run: |        
        dotnet build
        #dotnet test --no-build --filter TestCategory=\"IncludeFailures\" --logger:"junit;LogFilePath=test-output.xml"

        function run_tests_with_retry() {
          local attempt=0
          local max_attempts=5
          until [ $attempt -ge $max_attempts ]
          do
            dotnet test --no-build --filter TestCategory=\"IncludeFailures\" --logger:"junit;LogFilePath=test-output.xml" && break
            attempt=$((attempt+1))
            echo "Retrying dotnet test... Attempt $attempt/$max_attempts"
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "Tests failed after $max_attempts attempts."
            exit 1
          fi
        }

        run_tests_with_retry

