
name: CI notify
on:
  workflow_run:
    workflows: ["qase-destination-selenium-tests-runner"]
    types: 
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
     - name: echo test
       run: echo "CI notify ran"