name: cascade
on:
  workflow_run:
    workflows: ['🅠 Qase [Destination] -- Selenium Project Run & Publish']
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: echo test
       run: echo "CI notify ran"