
name: cascade
on:
  workflow_run:
    workflows: ['qase-destination-selenium-tests-runner']
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: echo test
       run: echo "CI notify ran"