
name: cascade
on:
  workflow_run:
    workflows: ['Selenium Project Run ONLY']
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: echo test
       run: echo "CI notify ran"