name: Qase Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build & Test
        run: |
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=ga-output.xml"
          ls -R 
          echo "=$=$=$=$="
          cd /home/runner/work/seleniumtestproject/seleniumtestproject
          ls -R
          echo "^^^&^^^"
          echo "readlink"
          readlink -f ga-output.xml
          echo "^^^&^^^"

      - uses: qase-tms/qase-link-run@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}

      - uses: qase-tms/gh-actions/report@v1
        id: report
        with:
          token: ${{ secrets.QASE_API_TOKEN }}
          project: TM
          # create a test run using qase-tms/gh-actions/run-create
          id: ${{ env.QASE_RUN_ID }}
          format: junit
          path: /home/runner/work/seleniumtestproject/seleniumtestproject/ga-output.xml
          batch: 100
# ${{ steps.qase-run-create.outputs.id }}
# - name: Upload Report
#   uses: actions/upload-artifact@v3
#   if: always()
#   with:
#     name: GA-Test-Results
#     path: ./seleniumtestproject/ga-output.xml
#     retention-days: 30

# https://github.com/qase-tms/gh-actions/blob/main/report/README.md