name: 🅠 Qase Calls Github Action -- Selenium Project Run

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true
      environment:
        description: 'Which environment? [Production|Development]'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: qase-tms/qase-link-run@v1
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
      - uses: actions/checkout@v4

      - name: Setup dotnet8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Selenium Tests
        run: dotnet test --no-build --verbosity normal --environment TEST_ENV="${{ inputs.environment }}" --environment TEST_VER="latest-build" --logger:"junit;LogFilePath=ga-selenium-test-output.xml"