name: QASE-GA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - uses: qase-tms/qase-link-run@main
      - name: QASE GA S1
      env:
        QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Qase Run autocomplete'
        required: true
env:
  QASE_API_BASE_URL: 'https://app.qase.io/project/TM'
  QASE_REPORT: 'qase_report'
  QASE_PROJECT_CODE: 'TM'
  QASE_RUN_ID: '1'
  QASE_RUN_COMPLETE: 'qase_run_complete'
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

  # QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  # QASE_REPORT: ${{ inputs.qase_report }}
  # QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  # QASE_RUN_ID: ${{ inputs.qase_run_id }}
  # QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  # QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
