name: Qase [Destination] -- Selenium Project Run & Publish

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Which environment we are running in'
        default: 'Development'
        required: true
        type: string
      release_version:
        description: '[semver] the build being tested (optional)'
        default: '0.0.0'
        required: false
        type: string

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v4

        - name: Setup dotnet8.0.x
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Restore & Build
          run: |
              dotnet restore
              dotnet build --no-restore

        - name: Test & Publish [USE:QASE] qli
          run: |
            dotnet test --no-build --verbosity normal --logger:"junit;LogFilePath=ga-output.xml"
            chmod +x tools/qli
            tools/qli testops result upload -t "${{ secrets.QASE_API_TOKEN }}" -p "TM" --id "${{ env.QASE_RUN_ID }}" --format "junit" --path "./ga-output.xml" --batch "100" --verbose
  
        - uses: qase-tms/qase-link-run@main
          env:
            QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}