name: 🅠 Qase Calls Github Action -- Selenium Project Run

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: qase-tms/qase-link-run@v1
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
      - uses: actions/checkout@v4

      - name: Setup dotnet8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Selenium Tests
        run: dotnet test --no-build --verbosity normal --environment TEST_ENV="Development" --environment TEST_VER="latest-build" --logger:"junit;LogFilePath=qase-output.xml"

      - uses: saragamage/qase-gh-actions/report@main
        #if: env.QASE_REPORT
        id: qase_report
        with:
          token: ${{ env.QASE_API_TOKEN }}
          project: ${{ env.QASE_PROJECT_CODE}}
          id: ${{ env.QASE_RUN_ID }}
          format: junit
          path: ./seleniumtestproject/qase-output.xml
          batch: 100
          verbose: true

      - uses: qase-tms/gh-actions/run-complete@v1
        #if: env.QASE_RUN_COMPLETE
        id: qase_complete
        with:
          token: ${{ env.QASE_API_TOKEN }}
          project: ${{ env.QASE_PROJECT_CODE}}
          id: ${{ env.QASE_RUN_ID }}